version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "80:80"
